### ISSUE TITLE
`get_all_droplets()` broken

### ISSUE THREAD

**Issue by WoLpH** [koalalorenzo/python-digitalocean#177]
The example from the readme:
```
import digitalocean
manager = digitalocean.Manager(token=TOKEN)
my_droplets = manager.get_all_droplets()
print(my_droplets)
```
Appears to be broken:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    my_droplets = manager.get_all_droplets()
  File "digitalocean/Manager.py", line 101, in get_all_droplets
    data = self.get_data("droplets/")
  File "digitalocean/Manager.py", line 45, in get_data
    return self.__deal_with_pagination(args[0], data, params)
  File "digitalocean/Manager.py", line 67, in __deal_with_pagination
    values.append(value)
AttributeError: 'dict' object has no attribute 'append'
```

Running version: `python-digitalocean==1.10.1`
On Python 3.5.2

It appears to have been broken in 1.10.0, it worked in 1.9.0

**Comment by koalalorenzo** [comment]
I have to investigate, probably related to #146
